wandb_version: 1

weights:
  desc: null
  value: weights/dingwei.pt
cfg:
  desc: null
  value: data/dingwei/yolov5s_dingwei.yaml
data:
  desc: null
  value: data/dingwei/dingwei.yaml
hyp:
  desc: null
  value:
    lr0: 0.001
    lrf: 0.2
    momentum: 0.937
    weight_decay: 0.00025
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    box: 0.05
    cls: 0.006250000000000001
    cls_pw: 1.0
    obj: 1.0
    obj_pw: 1.0
    iou_t: 0.2
    anchor_t: 4.0
    fl_gamma: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.0
epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 16
img_size:
  desc: null
  value:
  - 640
  - 640
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
noautoanchor:
  desc: null
  value: false
evolve:
  desc: null
  value: false
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
image_weights:
  desc: null
  value: false
device:
  desc: null
  value: '0'
multi_scale:
  desc: null
  value: false
single_cls:
  desc: null
  value: false
adam:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
log_imgs:
  desc: null
  value: 16
log_artifacts:
  desc: null
  value: false
workers:
  desc: null
  value: 0
project:
  desc: null
  value: runs/train
entity:
  desc: null
  value: null
name:
  desc: null
  value: exp
exist_ok:
  desc: null
  value: false
quad:
  desc: null
  value: false
linear_lr:
  desc: null
  value: false
world_size:
  desc: null
  value: 1
global_rank:
  desc: null
  value: -1
save_dir:
  desc: null
  value: runs\train\exp
total_batch_size:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712803235.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      - 61
      4: 3.10.14
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
